package mekanism.nuclear.common.config;

import java.io.File;
import net.minecraftforge.common.config.Configuration;

/** Server-authoritative stable fission reactor values. */
public final class NuclearFissionConfig {

    private static final String CATEGORY = "fission_reactor";

    public static final double AMBIENT_TEMPERATURE = 300D;
    public static final double BOIL_TEMPERATURE = 373.15D;
    public static final double MIN_DAMAGE_TEMPERATURE = 1_200D;
    public static final double MAX_DAMAGE_TEMPERATURE = 1_800D;
    public static final double MAX_DAMAGE = 100D;

    private static long energyPerFissionFuel;
    private static double casingHeatCapacity;
    private static double surfaceAreaTarget;
    private static double defaultBurnRate;
    private static long burnPerAssembly;
    private static long maxFuelPerAssembly;
    private static int cooledCoolantPerVolume;
    private static long heatedCoolantPerVolume;
    private static boolean meltdownsEnabled;
    private static float meltdownRadius;
    private static double meltdownChance;
    private static double meltdownRadiationMultiplier;
    private static double postMeltdownDamage;

    static {
        resetDefaults();
    }

    private NuclearFissionConfig() {
    }

    public static synchronized void load(File file) {
        Configuration config = new Configuration(file);
        config.load();
        energyPerFissionFuel = positiveLong(config, "EnergyPerFissionFuel", 1_000_000L,
              "Heat energy generated by each mB of Fissile Fuel.");
        casingHeatCapacity = config.get(CATEGORY, "CasingHeatCapacity", 1_000D,
              "Heat capacity contributed by each exterior reactor block.", 1, 1_000_000).getDouble();
        surfaceAreaTarget = config.get(CATEGORY, "SurfaceAreaTarget", 4D,
              "Average exposed fuel-assembly surface area required for full boil efficiency.", 1, Double.MAX_VALUE).getDouble();
        defaultBurnRate = config.get(CATEGORY, "DefaultBurnRate", 0.1D,
              "Default configured Fissile Fuel burn rate in mB/t.", 0.001D, 1D).getDouble();
        burnPerAssembly = positiveLong(config, "BurnPerAssembly", 1L,
              "Maximum burn rate in mB/t contributed by each fuel assembly block.");
        maxFuelPerAssembly = positiveLong(config, "MaxFuelPerAssembly", 8_000L,
              "Fuel and waste capacity in mB contributed by each fuel assembly block.");
        cooledCoolantPerVolume = config.getInt("CooledCoolantPerVolume", CATEGORY, 100_000,
              1, Integer.MAX_VALUE / (18 * 18 * 18), "Cooled coolant capacity per reactor block.");
        heatedCoolantPerVolume = positiveLong(config, "HeatedCoolantPerVolume", 1_000_000L,
              "Heated coolant capacity per reactor block.");
        meltdownsEnabled = config.getBoolean("MeltdownsEnabled", CATEGORY, true,
              "Whether critically damaged Fission Reactors can explode and release radiation.");
        meltdownRadius = (float) config.get(CATEGORY, "MeltdownRadius", 8D,
              "Explosion radius for a Fission Reactor meltdown.", 1, 500).getDouble();
        meltdownChance = config.get(CATEGORY, "MeltdownChance", 0.001D,
              "Per-tick meltdown chance at 100% damage; scales with excess damage.", 0, 1).getDouble();
        meltdownRadiationMultiplier = config.get(CATEGORY, "MeltdownRadiationMultiplier", 50D,
              "Multiplier applied to radioactive contents released by a meltdown.", 0.1D, 1_000_000D).getDouble();
        postMeltdownDamage = config.get(CATEGORY, "PostMeltdownDamage", 75D,
              "Damage retained after a meltdown.", 0, MAX_DAMAGE).getDouble();
        if (config.hasChanged()) {
            config.save();
        }
    }

    private static long positiveLong(Configuration config, String key, long fallback, String comment) {
        return NuclearConfigValues.getLong(config, CATEGORY, key, fallback, 1, comment);
    }

    public static long getEnergyPerFissionFuel() {
        return energyPerFissionFuel;
    }

    public static double getCasingHeatCapacity() {
        return casingHeatCapacity;
    }

    public static double getSurfaceAreaTarget() {
        return surfaceAreaTarget;
    }

    public static double getDefaultBurnRate() {
        return defaultBurnRate;
    }

    public static long getBurnPerAssembly() {
        return burnPerAssembly;
    }

    public static long getMaxFuelPerAssembly() {
        return maxFuelPerAssembly;
    }

    public static int getCooledCoolantPerVolume() {
        return cooledCoolantPerVolume;
    }

    public static long getHeatedCoolantPerVolume() {
        return heatedCoolantPerVolume;
    }

    public static boolean isMeltdownsEnabled() {
        return meltdownsEnabled;
    }

    public static float getMeltdownRadius() {
        return meltdownRadius;
    }

    public static double getMeltdownChance() {
        return meltdownChance;
    }

    public static double getMeltdownRadiationMultiplier() {
        return meltdownRadiationMultiplier;
    }

    public static double getPostMeltdownDamage() {
        return postMeltdownDamage;
    }

    static void resetDefaults() {
        energyPerFissionFuel = 1_000_000L;
        casingHeatCapacity = 1_000D;
        surfaceAreaTarget = 4D;
        defaultBurnRate = 0.1D;
        burnPerAssembly = 1L;
        maxFuelPerAssembly = 8_000L;
        cooledCoolantPerVolume = 100_000;
        heatedCoolantPerVolume = 1_000_000L;
        meltdownsEnabled = true;
        meltdownRadius = 8F;
        meltdownChance = 0.001D;
        meltdownRadiationMultiplier = 50D;
        postMeltdownDamage = 75D;
    }
}
