package mekanism.generators.common.integration;

import net.minecraftforge.common.config.Configuration;

/** Server-authoritative balance values for Generators' optional MekaSuit units. */
public final class GeneratorsMekaSuitConfig {

    public static final double DEFAULT_SOLAR_RECHARGING_RATE = 500D;
    public static final double DEFAULT_GEOTHERMAL_CHARGING_RATE = 10D;
    public static final double DEFAULT_HEAT_DAMAGE_REDUCTION_RATIO = 0.8D;

    public static double solarRechargingRate = DEFAULT_SOLAR_RECHARGING_RATE;
    public static double geothermalChargingRate = DEFAULT_GEOTHERMAL_CHARGING_RATE;
    public static double heatDamageReductionRatio = DEFAULT_HEAT_DAMAGE_REDUCTION_RATIO;

    private GeneratorsMekaSuitConfig() {
    }

    public static void load(Configuration config) {
        solarRechargingRate = config.get("mekasuit", "SolarRechargingRate", DEFAULT_SOLAR_RECHARGING_RATE,
              "Peak Joules per tick generated by each Solar Recharging Unit installed in a MekaSuit Helmet.",
              0D, Double.MAX_VALUE).getDouble();
        geothermalChargingRate = config.get("mekasuit", "GeothermalChargingRate", DEFAULT_GEOTHERMAL_CHARGING_RATE,
              "Joules per tick generated per degree above ambient and per Geothermal Generator Unit.",
              0D, Double.MAX_VALUE).getDouble();
        heatDamageReductionRatio = config.get("mekasuit", "HeatDamageReductionRatio", DEFAULT_HEAT_DAMAGE_REDUCTION_RATIO,
              "Maximum fraction of fire damage absorbed by eight Geothermal Generator Units.",
              0D, 1D).getDouble();
    }
}
